# Generated by Django 4.1.3 on 2022-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0002_alter_url_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='images/company logo'),
        ),
    ]
