# Generated by Django 4.1.3 on 2022-12-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0003_url_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='company_logo',
        ),
    ]
