# Generated by Django 4.1.3 on 2022-12-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0004_remove_url_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='user_otp_status',
        ),
    ]
