# Generated by Django 4.1.3 on 2022-12-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0005_rename_user_status_user_user_otp_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_otp_status',
            new_name='user_otp',
        ),
    ]
