# Generated by Django 4.1.3 on 2022-12-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0007_user_user_otp_status_alter_user_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_otp',
        ),
    ]
