# Generated by Django 4.1.3 on 2022-12-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0008_remove_user_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
