# Generated by Django 4.1.3 on 2022-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0009_user_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_otp_status',
            field=models.CharField(default='otp is pending', max_length=50),
        ),
    ]
