# Generated by Django 4.1.3 on 2022-12-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0010_alter_user_user_otp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('option5', models.CharField(max_length=50)),
                ('option6', models.CharField(max_length=50)),
                ('option7', models.CharField(max_length=50)),
                ('option8', models.CharField(max_length=50)),
                ('option9', models.CharField(max_length=50)),
                ('option10', models.CharField(max_length=50)),
                ('option11', models.CharField(max_length=50)),
                ('option12', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseakerapp.user')),
            ],
            options={
                'db_table': 'survey_details',
            },
        ),
    ]
