# Generated by Django 4.1.3 on 2022-12-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseakerapp', '0011_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='option1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
